---
# - name: Set Locale
#   ansible.builtin.shell:
#     cmd: LC_ALL

- include: user_wrangler.yml
  tags: user

- include_tasks: 
    file: "install/{{ ansible_facts['os_family'] | default('Suse') }}.yml"
    apply:
      tags: install
  tags: install
    

- include_tasks: 
    file: configure.yml
    apply:
      tags: configure
  tags: configure 
  ignore_errors: yes
